# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AFAccumulating' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod "AFNetworking"

  # Pods for AFAccumulating

  target 'AFAccumulatingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
